// Venue execution-adapter boundary. The executor speaks only this interface, so
// dry-run and each live venue share one code path. A leg's venue-native identifier
// (Kalshi ticker / Polymarket tokenId / SX marketHash) rides on the OrderRequest —
// live adapters refuse to place an order without it.

export type OrderFillStatus = "pending" | "filled" | "partial" | "unfilled" | "rejected";

export type ExpectedContractIdentity = {
  marketType: "moneyline" | "spread" | "total";
  line: number | null;
  outcome: string;
  teams: [string, string]; // canonical [away, home]
  sourceStartTime?: string;
};

export type OrderRequest = {
  venueId: string;
  // Our synthetic id (for logging) + the venue-native id/side actually used to order.
  marketId: string;
  nativeMarketId?: string;
  nativeSide?: string;
  outcome: string; // over/under/home/away (our canonical)
  // Immutable contract meaning captured when the venue-native market was normalized.
  expectedContract?: ExpectedContractIdentity;
  sizeContracts: number;
  limitPriceCents: number; // buy no higher than this
  // Deterministic identifier generated by the durable risk reservation. Adapters that
  // support caller-provided idempotency keys must forward this unchanged.
  clientOrderId?: string;
};

export type OrderResult = {
  ok: boolean;
  orderId: string | null;
  // Some venues acknowledge with a display/API id but require a hash for confirmation.
  confirmationId?: string | null;
  filledContracts: number;
  avgPriceCents: number;
  status: OrderFillStatus;
  error?: string;
  raw?: unknown;
};

// A fresh, venue-native executable quote taken immediately before placement. The
// executor uses the smallest availableContracts across every leg, then re-prices and
// re-checks the whole basket before sending any order.
export type ExecutableOrderQuote = {
  ok: boolean;
  priceCents: number; // worst price required to fill availableContracts
  averagePriceCents: number;
  availableContracts: number;
  // Fresh executable ask levels, cheapest first. Keeping the ladder lets the executor
  // optimize price and common contract count without making another network request for
  // every possible size. Venues that only expose top-of-book return one level.
  levels?: Array<{ priceCents: number; contracts: number }>;
  reason?: string;
};

// Post-placement settlement confirmation. On-chain venues (SX.bet especially) ack an
// order before it settles on-chain (PENDING → SUCCESS/FAILED), so the placement result
// is not final truth — reconciliation re-queries the venue to confirm.
export type FillConfirmation = {
  status: "settled" | "pending" | "failed" | "unknown";
  filledContracts?: number;
  avgPriceCents?: number;
  error?: string;
};

export interface ExecutionAdapter {
  id: string;
  // True only when real credentials / a wallet signer are configured for this venue.
  supportsLive(): boolean;
  // Account balance in USD, or null if unknown/unconfigured.
  getBalanceUsd(): Promise<number | null>;
  quoteOrder?(req: OrderRequest): Promise<ExecutableOrderQuote>;
  // Optional local preparation (for example, building/signing an order payload) performed
  // after exact pricing but before the durable submission fence. It must not contact a
  // mutating venue endpoint or place an order.
  prepareOrder?(req: OrderRequest): Promise<{ ok: boolean; reason?: string }>;
  placeOrder(req: OrderRequest): Promise<OrderResult>;
  // Read-only recovery by a deterministic client/reference id after a process dies before
  // receiving the venue response. Must never submit or retry an order.
  recoverOrder?(req: OrderRequest): Promise<OrderResult | null>;
  // Optional: re-query the venue to confirm an order actually settled. Absent ⇒ the
  // placement result is treated as authoritative (currently Kalshi IOC).
  confirmFill?(orderId: string, req: OrderRequest): Promise<FillConfirmation>;
}
